import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";
import {UserProvider} from "@/app/stores/UserContext";
import Header from "./components/Header";
import Footer from "./components/Footer";


const pacifico = Pacifico({
    weight: '400',
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-pacifico',
})

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Item Site",
    description: "Generated by Readdy",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
        >
        <UserProvider> {/*전역 유저 상태를 사용할 수 있게 앱 전체를 감싸주기*/}
            <Header />
        {children}
            <Footer />
        </UserProvider>
        </body>
        </html>
    );
}
